name: Deploy Development

on:
  push:
    branches: [dev]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage dev
        env:
          LAMBDA: true
          MONGO_URL: ${env:MONGO_URL}
          MONGO_DB: ${env:MONGO_DB}
